controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

app_charge_home:
    path: /
    controller: App\Controller\HomeController::index

app_charge_booking:
    path: /booking
    controller: App\Controller\BookingController::index

app_logout:
    path: /logout
    methods: GET